"""Traffic model: semantic collectives → physical flows.

Consumes three inputs and produces the flow-level work the GOAL emitter
renders:

1. **Collective trace** (schema ``simllm-collective-trace-v1``, JSONL): one
   record per communication op, i.e.
   ``{step, layer, op, group_type, group_global_ranks, send_counts,
   element_bytes, hidden_size, placement_epoch, release_time_ns}``
   with ``op`` in ALL_REDUCE / ALL_GATHER / REDUCE_SCATTER / ALL_TO_ALLV /
   SEND_RECV (PP), plus KV-transfer records.
2. **Placement manifest**: resolves group members to nodes/GPUs; for MoE,
   ``expert_owners[layer][global_expert_id]`` turns routed tokens into
   all-to-allv destinations at the correct ``placement_epoch``.
3. **Fabric manifest**: NIC selection, intra- vs inter-node split.

Semantic collectives are then expanded into the algorithm actually used
(ring, tree, pairwise all-to-allv, or a custom collective-network schedule)
as chunked send/recv chains, so the network simulator sees real traffic
patterns rather than abstract ops.
"""

COLLECTIVE_TRACE_SCHEMA = "simllm-collective-trace-v1"

from simllm.traffic.collective_latency import (
    A100_NCCL_2_31_CROSS_NODE_SOCKET_PROFILE,
    B200_NCCL_2_27_CROSS_NODE_PROVISIONAL_PROFILE,
    B200_NCCL_2_27_LOCAL_PROFILE,
    COLLECTIVE_EVIDENCE_CLASSES,
    COLLECTIVE_FIXED_COST_ARMS,
    COLLECTIVE_FIXED_COST_FLOOR_PROFILE,
    COLLECTIVE_PROPAGATION_REFERENCE_PS,
    CROSS_NODE_COLLECTIVE_FIXED_COST_ENVELOPE,
    FABRIC_RING_STEP_HIGH_PS,
    FABRIC_RING_STEP_LOW_PS,
    FABRIC_RING_STEP_POINT_PS,
    INTRA_NODE_COLLECTIVE_FIXED_COST_ENVELOPE,
    LEGACY_COLLECTIVE_LATENCY_PROFILE,
    NVLINK_RING_STEP_PS,
    ArmRatioEnvelope,
    CollectiveBandwidthCurve,
    CollectiveFixedCostEnvelope,
    CollectiveLatencyProfile,
    CollectiveLatencyProvenance,
    arm_ratio_envelope,
    critical_collective_endpoint_bytes,
    resolve_collective_fixed_cost_envelope,
    resolve_collective_latency_profile,
)
from simllm.traffic.collective_plan import (
    DEFAULT_COLLECTIVE_PLAN_BASE_TAG,
    collective_plan_by_operation,
    plan_execution_graph_collectives,
    render_collective_plan,
)
from simllm.traffic.execution_goal import (
    ExecutionGoalArtifact,
    ExecutionGoalArtifactBoundary,
    ExecutionGoalProjection,
    project_execution_graph_goal,
    render_serial_execution_graph_goal,
    verify_execution_goal_projection,
)
from simllm.traffic.locality import (
    DEFAULT_NVLINK_BANDWIDTH_BYTES_PER_SECOND,
    ClassifiedCommunicationPhase,
    CollectiveCommunicationPhase,
    DirectedCollectiveSegment,
    StepLocalityPlan,
    classify_step_locality,
)
from simllm.traffic.patterns import (
    binomial_broadcast,
    gather,
    ordered_pairwise_messages,
    pairwise_all_to_allv,
    ring_allreduce,
    scatter,
)
from simllm.traffic.request_fidelity import (
    RequestFidelityError,
    RequestFidelityReport,
    compare_goal_request_attribution,
)
from simllm.traffic.routed_conservation import (
    ALWAYS_APPLIED_RULES,
    CAPTURED_ONLY_RULES,
    CONSERVATION_RULES,
    ROUTED_EVIDENCE_CAPTURED,
    ROUTED_EVIDENCE_MODES,
    ROUTED_EVIDENCE_UNIFORM,
    RoutedConservationReport,
    RoutedPhaseTable,
    RoutedTokenOwnership,
    routed_moe_conservation_report,
)
from simllm.traffic.routed_moe import (
    ExpertPlacementSnapshot,
    RoutedMoeSupply,
    validate_expert_placement_snapshot,
    validate_routed_moe_supply,
)
from simllm.traffic.step_comm import (
    EXPERT_PARALLEL_TP_ALLREDUCE_SITES,
    MOE_A2A_PHASES,
    OBSERVED_ABSENT_BYTE_EVIDENCE,
    OBSERVED_MIXED_BYTE_EVIDENCE,
    OBSERVED_NO_BYTE_EVIDENCE,
    OBSERVED_PAIR_TABLE_EVIDENCE,
    TP_ALLREDUCE_SITES,
    MoeAllToAll,
    MoeMessageGrouping,
    MoeMessageSequence,
    RoutedMoeMessage,
    TpAllReduce,
    compare_request_moe_fidelity,
    layer_tp_allreduce_sites,
    lower_step_observations,
    observed_routed_byte_evidence,
    plan_execution_graph_locality,
    plan_step_locality,
    render_fabric_phase_goal,
    render_sequenced_step_goal,
    render_step_goal,
    renders_expert_combine,
    routed_moe_conservation,
    step_communication_phases,
    step_moe_alltoalls,
    step_moe_message_sequences,
    step_tp_allreduces,
    validate_execution_graph_locality_projection,
    validate_request_moe_fidelity,
)

__all__ = [
    "A100_NCCL_2_31_CROSS_NODE_SOCKET_PROFILE",
    "ALWAYS_APPLIED_RULES",
    "B200_NCCL_2_27_CROSS_NODE_PROVISIONAL_PROFILE",
    "B200_NCCL_2_27_LOCAL_PROFILE",
    "CAPTURED_ONLY_RULES",
    "COLLECTIVE_EVIDENCE_CLASSES",
    "COLLECTIVE_FIXED_COST_ARMS",
    "COLLECTIVE_FIXED_COST_FLOOR_PROFILE",
    "COLLECTIVE_PROPAGATION_REFERENCE_PS",
    "COLLECTIVE_TRACE_SCHEMA",
    "CONSERVATION_RULES",
    "CROSS_NODE_COLLECTIVE_FIXED_COST_ENVELOPE",
    "DEFAULT_COLLECTIVE_PLAN_BASE_TAG",
    "DEFAULT_NVLINK_BANDWIDTH_BYTES_PER_SECOND",
    "EXPERT_PARALLEL_TP_ALLREDUCE_SITES",
    "FABRIC_RING_STEP_HIGH_PS",
    "FABRIC_RING_STEP_LOW_PS",
    "FABRIC_RING_STEP_POINT_PS",
    "INTRA_NODE_COLLECTIVE_FIXED_COST_ENVELOPE",
    "LEGACY_COLLECTIVE_LATENCY_PROFILE",
    "MOE_A2A_PHASES",
    "NVLINK_RING_STEP_PS",
    "OBSERVED_ABSENT_BYTE_EVIDENCE",
    "OBSERVED_MIXED_BYTE_EVIDENCE",
    "OBSERVED_NO_BYTE_EVIDENCE",
    "OBSERVED_PAIR_TABLE_EVIDENCE",
    "ROUTED_EVIDENCE_CAPTURED",
    "ROUTED_EVIDENCE_MODES",
    "ROUTED_EVIDENCE_UNIFORM",
    "TP_ALLREDUCE_SITES",
    "ArmRatioEnvelope",
    "ClassifiedCommunicationPhase",
    "CollectiveBandwidthCurve",
    "CollectiveCommunicationPhase",
    "CollectiveFixedCostEnvelope",
    "CollectiveLatencyProfile",
    "CollectiveLatencyProvenance",
    "DirectedCollectiveSegment",
    "ExecutionGoalArtifact",
    "ExecutionGoalArtifactBoundary",
    "ExecutionGoalProjection",
    "ExpertPlacementSnapshot",
    "MoeAllToAll",
    "MoeMessageGrouping",
    "MoeMessageSequence",
    "RequestFidelityError",
    "RequestFidelityReport",
    "RoutedConservationReport",
    "RoutedMoeMessage",
    "RoutedMoeSupply",
    "RoutedPhaseTable",
    "RoutedTokenOwnership",
    "StepLocalityPlan",
    "TpAllReduce",
    "arm_ratio_envelope",
    "binomial_broadcast",
    "classify_step_locality",
    "collective_plan_by_operation",
    "compare_goal_request_attribution",
    "compare_request_moe_fidelity",
    "critical_collective_endpoint_bytes",
    "gather",
    "layer_tp_allreduce_sites",
    "lower_step_observations",
    "observed_routed_byte_evidence",
    "ordered_pairwise_messages",
    "pairwise_all_to_allv",
    "plan_execution_graph_collectives",
    "plan_execution_graph_locality",
    "plan_step_locality",
    "project_execution_graph_goal",
    "render_collective_plan",
    "render_fabric_phase_goal",
    "render_sequenced_step_goal",
    "render_serial_execution_graph_goal",
    "render_step_goal",
    "renders_expert_combine",
    "resolve_collective_fixed_cost_envelope",
    "resolve_collective_latency_profile",
    "ring_allreduce",
    "routed_moe_conservation",
    "routed_moe_conservation_report",
    "scatter",
    "step_communication_phases",
    "step_moe_alltoalls",
    "step_moe_message_sequences",
    "step_tp_allreduces",
    "validate_execution_graph_locality_projection",
    "validate_expert_placement_snapshot",
    "validate_request_moe_fidelity",
    "validate_routed_moe_supply",
    "verify_execution_goal_projection",
]
