"""Network-backend invocation: htsim (packet-level) and LogGOPSim (flow-level)."""

from simllm.backends.composed_rnic import (
    NATIVE_AUTHORITY,
    ComposedRnicCell,
    ComposedRnicObservationError,
    ComposedRnicObservations,
    ComposedRnicSession,
    ComposedWqeObservation,
    invoke_composed_tier_a_producer,
)
from simllm.backends.dependency_cross_check import (
    DependencyCrossCheckPlan,
    DependencyCrossCheckReport,
    DependencyOrderingComparison,
    DependencyPhaseFrontierComparison,
    complete_dependency_cross_check,
    plan_dependency_cross_check,
)
from simllm.backends.device_step_sink import DeviceRuntimeStepSink, DeviceStepOutcome
from simllm.backends.fct import NormalizedFct, normalized_fct
from simllm.backends.htsim import HtsimUecConfig, build_htsim_uec_command
from simllm.backends.htsim_dcqcn import (
    HtsimDcqcnConfig,
    build_htsim_dcqcn_command,
    find_htsim_dcqcn,
    run_htsim_dcqcn,
)
from simllm.backends.htsim_rnic import (
    RNIC_PROFILES,
    FlowCompletion,
    HtsimRnicConfig,
    RnicRunResult,
    build_htsim_rnic_command,
    find_htsim_rnic,
    parse_completion_csv,
    run_htsim_rnic,
)
from simllm.backends.loggopsim import (
    LOGGOPSIM_NETWORK_TYPES,
    LogGopsimConfig,
    LogGopsimRunResult,
    build_loggopsim_command,
    find_loggopsim,
    parse_loggopsim_stdout,
    run_loggopsim,
)
from simllm.backends.rnic_records import (
    BypassArtifactComparison,
    BypassArtifactPaths,
    BypassArtifacts,
    RnicAuthorityCounters,
    RnicBookkeepingProjection,
    RnicCompletionProjection,
    RnicHardwareMode,
    RnicSessionConfigRecord,
    RnicSessionResultRecord,
    RnicWqeAuthority,
    RnicWqeProjectionKey,
    RnicWqeProjectionRecord,
    RnicWqeTimeline,
    assert_bypass_artifact_identity,
    canonical_bypass_parameters,
    compare_bypass_artifacts,
    read_bypass_artifacts,
    rnic_bookkeeping_projection_from_json,
    rnic_session_config_from_json,
    rnic_session_result_from_json,
)
from simllm.backends.step_lowerer import (
    ObservedStepLowerer,
    SerialStepLowerer,
    SerialStepLowererConfig,
    SerialStepTiming,
)
from simllm.backends.step_sink import (
    DEPENDENCY_CROSS_CHECK_MODES,
    HtsimPersistentStepSink,
    HtsimStepSink,
    HtsimStepSinkConfig,
    StepLocalityOutcome,
    StepNetworkOutcome,
)

__all__ = [
    "DEPENDENCY_CROSS_CHECK_MODES",
    "LOGGOPSIM_NETWORK_TYPES",
    "NATIVE_AUTHORITY",
    "RNIC_PROFILES",
    "BypassArtifactComparison",
    "BypassArtifactPaths",
    "BypassArtifacts",
    "ComposedRnicCell",
    "ComposedRnicObservationError",
    "ComposedRnicObservations",
    "ComposedRnicSession",
    "ComposedWqeObservation",
    "DependencyCrossCheckPlan",
    "DependencyCrossCheckReport",
    "DependencyOrderingComparison",
    "DependencyPhaseFrontierComparison",
    "DeviceRuntimeStepSink",
    "DeviceStepOutcome",
    "FlowCompletion",
    "HtsimDcqcnConfig",
    "HtsimPersistentStepSink",
    "HtsimRnicConfig",
    "HtsimStepSink",
    "HtsimStepSinkConfig",
    "HtsimUecConfig",
    "LogGopsimConfig",
    "LogGopsimRunResult",
    "NormalizedFct",
    "ObservedStepLowerer",
    "RnicAuthorityCounters",
    "RnicBookkeepingProjection",
    "RnicCompletionProjection",
    "RnicHardwareMode",
    "RnicRunResult",
    "RnicSessionConfigRecord",
    "RnicSessionResultRecord",
    "RnicWqeAuthority",
    "RnicWqeProjectionKey",
    "RnicWqeProjectionRecord",
    "RnicWqeTimeline",
    "SerialStepLowerer",
    "SerialStepLowererConfig",
    "SerialStepTiming",
    "StepLocalityOutcome",
    "StepNetworkOutcome",
    "assert_bypass_artifact_identity",
    "build_htsim_dcqcn_command",
    "build_htsim_rnic_command",
    "build_htsim_uec_command",
    "build_loggopsim_command",
    "canonical_bypass_parameters",
    "compare_bypass_artifacts",
    "complete_dependency_cross_check",
    "find_htsim_dcqcn",
    "find_htsim_rnic",
    "find_loggopsim",
    "invoke_composed_tier_a_producer",
    "normalized_fct",
    "parse_completion_csv",
    "parse_loggopsim_stdout",
    "plan_dependency_cross_check",
    "read_bypass_artifacts",
    "rnic_bookkeeping_projection_from_json",
    "rnic_session_config_from_json",
    "rnic_session_result_from_json",
    "run_htsim_dcqcn",
    "run_htsim_rnic",
    "run_loggopsim",
]
