"""Network-backend invocation: htsim (packet-level) and LogGOPSim (flow-level)."""

from simllm.backends.composed_rnic import (
    NATIVE_AUTHORITY,
    ComposedRnicCell,
    ComposedRnicObservationError,
    ComposedRnicObservations,
    ComposedRnicSession,
    ComposedWqeObservation,
    invoke_composed_tier_a_producer,
)
from simllm.backends.fct import NormalizedFct, normalized_fct
from simllm.backends.htsim import HtsimUecConfig, build_htsim_uec_command
from simllm.backends.htsim_dcqcn import (
    HtsimDcqcnConfig,
    build_htsim_dcqcn_command,
    find_htsim_dcqcn,
    run_htsim_dcqcn,
)
from simllm.backends.htsim_rnic import (
    RNIC_PROFILES,
    FlowCompletion,
    HtsimRnicConfig,
    RnicRunResult,
    build_htsim_rnic_command,
    find_htsim_rnic,
    parse_completion_csv,
    run_htsim_rnic,
)
from simllm.backends.rnic_records import (
    BypassArtifactComparison,
    BypassArtifactPaths,
    BypassArtifacts,
    RnicAuthorityCounters,
    RnicBookkeepingProjection,
    RnicCompletionProjection,
    RnicHardwareMode,
    RnicSessionConfigRecord,
    RnicSessionResultRecord,
    RnicWqeAuthority,
    RnicWqeProjectionKey,
    RnicWqeProjectionRecord,
    RnicWqeTimeline,
    assert_bypass_artifact_identity,
    canonical_bypass_parameters,
    compare_bypass_artifacts,
    read_bypass_artifacts,
    rnic_bookkeeping_projection_from_json,
    rnic_session_config_from_json,
    rnic_session_result_from_json,
)
from simllm.backends.step_lowerer import SerialStepLowerer, SerialStepLowererConfig
from simllm.backends.step_sink import (
    HtsimPersistentStepSink,
    HtsimStepSink,
    HtsimStepSinkConfig,
    StepNetworkOutcome,
)

__all__ = [
    "NATIVE_AUTHORITY",
    "RNIC_PROFILES",
    "BypassArtifactComparison",
    "BypassArtifactPaths",
    "BypassArtifacts",
    "ComposedRnicCell",
    "ComposedRnicObservationError",
    "ComposedRnicObservations",
    "ComposedRnicSession",
    "ComposedWqeObservation",
    "FlowCompletion",
    "HtsimDcqcnConfig",
    "HtsimPersistentStepSink",
    "HtsimRnicConfig",
    "HtsimStepSink",
    "HtsimStepSinkConfig",
    "HtsimUecConfig",
    "NormalizedFct",
    "RnicAuthorityCounters",
    "RnicBookkeepingProjection",
    "RnicCompletionProjection",
    "RnicHardwareMode",
    "RnicRunResult",
    "RnicSessionConfigRecord",
    "RnicSessionResultRecord",
    "RnicWqeAuthority",
    "RnicWqeProjectionKey",
    "RnicWqeProjectionRecord",
    "RnicWqeTimeline",
    "SerialStepLowerer",
    "SerialStepLowererConfig",
    "StepNetworkOutcome",
    "assert_bypass_artifact_identity",
    "build_htsim_dcqcn_command",
    "build_htsim_rnic_command",
    "build_htsim_uec_command",
    "canonical_bypass_parameters",
    "compare_bypass_artifacts",
    "find_htsim_dcqcn",
    "find_htsim_rnic",
    "invoke_composed_tier_a_producer",
    "normalized_fct",
    "parse_completion_csv",
    "read_bypass_artifacts",
    "rnic_bookkeeping_projection_from_json",
    "rnic_session_config_from_json",
    "rnic_session_result_from_json",
    "run_htsim_dcqcn",
    "run_htsim_rnic",
]
