#!/usr/bin/env python3
"""kernel_determinism_v1: the kernel-time determinism contract.

Harness for the freeze in ``expectations.md``. It measures the observable
consequences of the maintainer's 2026-08-18 ruling that a compute kernel's
service time is a deterministic constant with no tail, a pure function of
kernel family, phase, token and shape inputs, and the architecture profile.

Evidence classes are kept apart and are never added into one total:

``fatal_guard``
    Voids the run when violated. Never reported as a fraction. Determinism of a
    deterministic function is entailed by its construction, so the repeat and
    fresh-instance rows live here rather than in the scored denominator.
``control``
    Proves a guard or a scored row is discriminating. A control that fails to
    fail is itself a finding.
``scored``
    The eight genuine-risk instances of the freeze, each an exact integer
    predicted before the implementation existed.
``derived``
    Arithmetic over rows already scored. Reported, never counted.
``observation``
    Raw configuration facts. Assert nothing.

Run it with no arguments to regenerate ``results.json`` beside this file, or
with ``--check`` to require the regenerated bytes to equal the committed
artifact.
"""

from __future__ import annotations

import argparse
import ast
import importlib.util
import inspect
import json
import sys
from collections.abc import Iterable
from dataclasses import dataclass, fields, is_dataclass
from enum import Enum
from pathlib import Path
from types import SimpleNamespace
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from simllm.compute import (
    ComputeProvider,
    GpuPortCapability,
    GpuPortConfig,
    GpuPortDirection,
    GpuPortProtocol,
    GpuPortRole,
    GpuSpec,
    HostInitiationModel,
    ModelDims,
    RooflineProvider,
    SmSchedulerModel,
    estimate_step_latency_ps,
    step_kernel,
    step_kernels,
)
from simllm.core import RequestPhase, ScheduledRequest, StepRecord

SCHEMA = "simllm-kernel-determinism-v1"
FREEZE = "examples/kernel_determinism_v1/expectations.md"
RESULTS = Path(__file__).resolve().parent / "results.json"

FATAL_GUARD = "fatal_guard"
CONTROL = "control"
SCORED = "scored"
DERIVED = "derived"
OBSERVATION = "observation"

#: repeats behind guard G1; one instance priced this many times
REPEATS = 64

# ---------------------------------------------------------------------------
# Fixture R, the roofline step (expectations.md, "Fixtures")
# ---------------------------------------------------------------------------

NUM_LAYERS = 2
HIDDEN_SIZE = 128
INTERMEDIATE_SIZE = 256
NUM_HEADS = 4
NUM_KV_HEADS = 2
HEAD_SIZE = 32
VOCAB_SIZE = 1024
DTYPE_BYTES = 2

#: exact powers of two so the provider's IEEE-754 double arithmetic is exact
PEAK_FLOPS = float(2**48)
MEM_BANDWIDTH = float(2**41)
EFFICIENCY = 0.5

# ---------------------------------------------------------------------------
# Fixture M, the mechanistic HBM cursor (the accepted gpu_task_mix fixture)
# ---------------------------------------------------------------------------

MECHANISTIC_TRANSACTION_BYTES = 192
MECHANISTIC_WARPS = 8
MECHANISTIC_PER_WARP = 4


def _load(name: str, relative: str) -> Any:
    """Load an accepted study as a module so its own fixtures are used."""

    path = REPO_ROOT / relative
    spec = importlib.util.spec_from_file_location(name, path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load accepted study {relative}")
    module = importlib.util.module_from_spec(spec)
    # Register before executing: a loaded study defines dataclasses, and
    # dataclasses resolves annotations through sys.modules while the body runs.
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


TASK_MIX = _load(
    "kernel_determinism_task_mix", "examples/gpu_task_mix/run_gpu_task_mix.py"
)


@dataclass(frozen=True)
class Row:
    row_id: str
    evidence_class: str
    family: str
    case: str
    expected: Any
    measured: Any

    @property
    def passed(self) -> bool:
        return self.expected == self.measured

    @property
    def status(self) -> str:
        if self.evidence_class == OBSERVATION:
            return "REPORTED"
        return "PASS" if self.passed else "FAIL"

    def to_json(self) -> dict[str, Any]:
        return {
            "id": self.row_id,
            "evidence_class": self.evidence_class,
            "family": self.family,
            "case": self.case,
            "expected": self.expected,
            "measured": self.measured,
            "status": self.status,
        }


# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


def model_dims() -> ModelDims:
    """The dense per-rank geometry frozen as fixture R."""

    return ModelDims(
        num_layers=NUM_LAYERS,
        hidden_size=HIDDEN_SIZE,
        intermediate_size=INTERMEDIATE_SIZE,
        num_heads=NUM_HEADS,
        num_kv_heads=NUM_KV_HEADS,
        head_size=HEAD_SIZE,
        vocab_size=VOCAB_SIZE,
        dtype_bytes=DTYPE_BYTES,
    )


def gpu_spec() -> GpuSpec:
    """The synthetic power-of-two envelope frozen as fixture R."""

    return GpuSpec(
        name="kernel-determinism-fixture",
        peak_flops=PEAK_FLOPS,
        mem_bandwidth=MEM_BANDWIDTH,
    )


def roofline(efficiency: float = EFFICIENCY) -> RooflineProvider:
    return RooflineProvider(efficiency=efficiency)


def decode_record(requests: int, *, context_length: int = 64) -> StepRecord:
    """One decode step with ``requests`` single-token continuations."""

    scheduled = [
        ScheduledRequest(
            f"d{index}",
            RequestPhase.DECODE,
            1,
            context_length=context_length,
        )
        for index in range(requests)
    ]
    return StepRecord(
        step_index=0,
        virtual_time_ps=0,
        scheduled=scheduled,
        num_sampled=requests,
        sampled_request_ids=[request.request_id for request in scheduled],
    )


def prefill_record(chunk_tokens: int) -> StepRecord:
    """One prefill step of a single ``chunk_tokens``-token chunk."""

    scheduled = [
        ScheduledRequest(
            "p0",
            RequestPhase.PREFILL,
            chunk_tokens,
            context_length=chunk_tokens,
        )
    ]
    return StepRecord(
        step_index=0,
        virtual_time_ps=0,
        scheduled=scheduled,
        num_sampled=1,
        sampled_request_ids=["p0"],
    )


#: (row id, label, record factory, sampled count) for the four frozen R cells
ROOFLINE_CELLS: tuple[tuple[str, str, Any, int], ...] = (
    ("A1", "decode,requests=2", lambda: decode_record(2), 2),
    ("A2", "decode,requests=4", lambda: decode_record(4), 4),
    ("A3", "prefill,tokens=512", lambda: prefill_record(512), 1),
    ("A4", "prefill,tokens=1024", lambda: prefill_record(1024), 1),
)

#: frozen predictions, from expectations.md, written before the harness existed
ROOFLINE_PREDICTIONS: dict[str, tuple[int, str]] = {
    "A1": (834_465, "memory"),
    "A2": (894_069, "memory"),
    "A3": (3_101_304, "compute"),
    "A4": (8_108_094, "compute"),
}

#: (row id, cursor bandwidth bytes/cycle, sm count, predicted cycles)
MECHANISTIC_CELLS: tuple[tuple[str, int, int, int], ...] = (
    ("B1", 64, 1, 196),
    ("B2", 32, 1, 292),
    ("C1", 64, 2, 196),
)


def mechanistic_launch():
    """The accepted task-mix memory launch at the freeze's new byte size."""

    return TASK_MIX.memory_launch(
        warps=MECHANISTIC_WARPS,
        per_warp=MECHANISTIC_PER_WARP,
        transaction_bytes=MECHANISTIC_TRANSACTION_BYTES,
    )


def mechanistic_model(*, hbm_bandwidth: int, sm_count: int) -> SmSchedulerModel:
    return SmSchedulerModel(
        TASK_MIX.architecture(sm_count=sm_count, hbm_bandwidth=hbm_bandwidth)
    )


# ---------------------------------------------------------------------------
# Fixture A, the two adapter geometry readers
# ---------------------------------------------------------------------------


def vllm_config() -> SimpleNamespace:
    """A dense vLLM config shaped to fixture R, with no field defaulted."""

    text = SimpleNamespace(
        model_type="llama",
        architectures=["LlamaForCausalLM"],
        intermediate_size=INTERMEDIATE_SIZE,
    )

    class _ModelConfig:
        dtype = SimpleNamespace(itemsize=DTYPE_BYTES)
        hf_text_config = text
        hf_config = text
        is_moe = False

        @staticmethod
        def get_hidden_size() -> int:
            return HIDDEN_SIZE

        @staticmethod
        def get_num_layers(parallel_config: Any) -> int:
            return NUM_LAYERS

        @staticmethod
        def get_num_attention_heads(parallel_config: Any) -> int:
            return NUM_HEADS

        @staticmethod
        def get_num_kv_heads(parallel_config: Any) -> int:
            return NUM_KV_HEADS

        @staticmethod
        def get_head_size() -> int:
            return HEAD_SIZE

        @staticmethod
        def get_vocab_size() -> int:
            return VOCAB_SIZE

    return SimpleNamespace(
        model_config=_ModelConfig(),
        cache_config=SimpleNamespace(block_size=16, cache_dtype="auto"),
        parallel_config=SimpleNamespace(
            data_parallel_size=1,
            prefill_context_parallel_size=1,
            tensor_parallel_size=1,
            pipeline_parallel_size=1,
            rank=0,
            enable_expert_parallel=False,
            eplb_config=SimpleNamespace(num_redundant_experts=0),
        ),
        quant_config=None,
    )


def sglang_model_config() -> Any:
    """A dense SGLang config shaped to fixture R, with no field defaulted."""

    hf = SimpleNamespace(
        hidden_size=HIDDEN_SIZE,
        intermediate_size=INTERMEDIATE_SIZE,
        num_attention_heads=NUM_HEADS,
        num_key_value_heads=NUM_KV_HEADS,
        vocab_size=VOCAB_SIZE,
    )

    class _ModelConfig:
        hf_text_config = hf
        num_hidden_layers = NUM_LAYERS
        num_attention_heads = NUM_HEADS
        head_dim = HEAD_SIZE
        vocab_size = VOCAB_SIZE
        dtype = SimpleNamespace(itemsize=DTYPE_BYTES)

        @staticmethod
        def get_num_kv_heads(tp_size: int) -> int:
            return max(NUM_KV_HEADS // max(int(tp_size), 1), 1)

    return _ModelConfig()


def adapter_dims() -> tuple[ModelDims, ModelDims]:
    """The two adapters' own readers on equivalent dense configs."""

    from simllm.adapters.sglang.worker import model_dims_from_sglang
    from simllm.adapters.vllm.executor import model_dims_from_vllm_config

    return (
        model_dims_from_vllm_config(vllm_config()),
        model_dims_from_sglang(sglang_model_config(), tp_size=1),
    )


def cost_geometry(dims: ModelDims) -> dict[str, Any]:
    """Every geometry value the step-cost model actually reads.

    Deliberately not dataclass equality: the two readers spell the optional
    dtype widths differently (an explicit float against ``None``), and the cost
    model reads both through the resolved-width properties.
    """

    return {
        "num_layers": dims.num_layers,
        "hidden_size": dims.hidden_size,
        "intermediate_size": dims.intermediate_size,
        "num_heads": dims.num_heads,
        "num_kv_heads": dims.num_kv_heads,
        "head_size": dims.head_size,
        "vocab_size": dims.vocab_size,
        "dtype_bytes": dims.dtype_bytes,
        "weight_element_bytes": dims.weight_element_bytes,
        "kv_element_bytes": dims.kv_element_bytes,
        "num_experts": dims.num_experts,
        "top_k": dims.top_k,
        "moe_intermediate_size": dims.moe_intermediate_size,
        "local_num_experts": dims.local_num_experts,
        "defaulted_fields": list(dims.defaulted_fields),
        "weight_bytes": dims.weight_bytes,
        "lm_head_bytes": dims.lm_head_bytes,
    }


# ---------------------------------------------------------------------------
# Canonical serialization: what "byte-equal" means here
# ---------------------------------------------------------------------------


def _plain(value: Any) -> Any:
    if is_dataclass(value) and not isinstance(value, type):
        return {
            field.name: _plain(getattr(value, field.name)) for field in fields(value)
        }
    if isinstance(value, Enum):
        return value.value
    if isinstance(value, (list, tuple)):
        return [_plain(item) for item in value]
    if isinstance(value, dict):
        return {str(key): _plain(item) for key, item in value.items()}
    return value


def canonical(value: Any) -> bytes:
    """One byte string per estimate, stable across processes and instances."""

    return json.dumps(
        _plain(value), sort_keys=True, separators=(",", ":")
    ).encode("utf-8")


# ---------------------------------------------------------------------------
# Guards G4 and G5: the audits, implemented once and reused by the test suite
# ---------------------------------------------------------------------------

#: modules whose import into a service path would make a duration nondeterministic
NONDETERMINISM_SOURCES = (
    "random",
    "secrets",
    "time",
    "datetime",
    "uuid",
    "os",
    "socket",
    "platform",
    "getpass",
    "tempfile",
    "numpy.random",
)


def imported_modules(path: Path) -> set[str]:
    """Top-level module names imported by one source file, from its AST."""

    tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    found: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                found.add(alias.name)
        elif isinstance(node, ast.ImportFrom) and node.module and node.level == 0:
            found.add(node.module)
    return found


def compute_module_paths() -> list[Path]:
    return sorted((REPO_ROOT / "simllm" / "compute").glob("*.py"))


def nondeterminism_audit(paths: Iterable[Path] | None = None) -> dict[str, list[str]]:
    """Every audited module that imports a nondeterminism source.

    ``paths`` defaults to the whole ``simllm/compute`` package. It is a
    parameter so the control can hand the audit a file that really does import
    one, which is the only way to know the audit is reading imports rather than
    returning an empty dictionary.
    """

    offenders: dict[str, list[str]] = {}
    for path in compute_module_paths() if paths is None else paths:
        hits = sorted(
            name
            for name in imported_modules(path)
            if name in NONDETERMINISM_SOURCES
            or any(name.startswith(f"{source}.") for source in NONDETERMINISM_SOURCES)
        )
        if hits:
            offenders[path.name] = hits
    return offenders


#: parameter-name fragments that would make a price depend on who asked
IDENTITY_PARAMETERS = ("rank", "worker", "adapter", "device_index", "gpu_index", "gpu_id")


#: modules that define a shipped ``ComputeProvider``. They are imported before
#: the sweep so the subclass set is complete no matter what else the process has
#: loaded, and the sweep keeps only ``simllm.`` classes so a study's own throwaway
#: fixture provider cannot change what this audit covers. Without both halves the
#: audited set depends on import order, which the artifact byte lock caught.
FIRST_PARTY_PROVIDER_MODULES = (
    "simllm.compute.provider",
    "simllm.compute.gpu_model",
    "simllm.adapters.sglang.host",
)


def first_party_providers() -> list[type]:
    """Every shipped ``ComputeProvider`` subclass, in a stable order."""

    for module in FIRST_PARTY_PROVIDER_MODULES:
        importlib.import_module(module)
    found: dict[str, type] = {}
    pending = list(ComputeProvider.__subclasses__())
    while pending:
        subclass = pending.pop()
        pending.extend(subclass.__subclasses__())
        if subclass.__module__.startswith("simllm."):
            found[f"{subclass.__module__}.{subclass.__qualname__}"] = subclass
    return [found[key] for key in sorted(found)]


def pricing_entry_points() -> dict[str, Any]:
    """Every callable that turns work into a duration."""

    entries: dict[str, Any] = {
        "ComputeProvider.estimate": ComputeProvider.estimate,
        "ComputeProvider.estimate_layers": ComputeProvider.estimate_layers,
        "SmSchedulerModel.estimate": SmSchedulerModel.estimate,
        "SmSchedulerModel.estimate_concurrent": SmSchedulerModel.estimate_concurrent,
        "transformer.step_kernel": step_kernel,
        "transformer.step_kernels": step_kernels,
        "transformer.estimate_step_latency_ps": estimate_step_latency_ps,
        "HostInitiationModel.represented_estimate": (
            HostInitiationModel.represented_estimate
        ),
    }
    for subclass in first_party_providers():
        key = f"{subclass.__name__}.estimate"
        if key in entries:
            key = f"{subclass.__module__}.{subclass.__qualname__}.estimate"
        entries[key] = subclass.estimate
    return entries


def identity_parameter_audit(
    entries: dict[str, Any] | None = None,
) -> dict[str, list[str]]:
    """Every pricing entry point that accepts a caller-identity parameter.

    ``entries`` defaults to :func:`pricing_entry_points`. It is a parameter for
    the same reason the import audit takes paths: the control needs to hand the
    audit a signature that really does key on a rank.
    """

    offenders: dict[str, list[str]] = {}
    for name, function in sorted(
        (pricing_entry_points() if entries is None else entries).items()
    ):
        hits = [
            parameter
            for parameter in inspect.signature(function).parameters
            if any(fragment in parameter.lower() for fragment in IDENTITY_PARAMETERS)
        ]
        if hits:
            offenders[name] = hits
    return offenders


# ---------------------------------------------------------------------------
# The checks
# ---------------------------------------------------------------------------


def _roofline_estimate(provider: RooflineProvider, record: StepRecord, sampled: int):
    return provider.estimate(step_kernel(model_dims(), record, sampled), gpu_spec())


def guard_repeat_determinism(rows: list[Row]) -> None:
    """G1: repeated estimates through one instance are one byte string."""

    provider = roofline()
    for row_id, label, factory, sampled in ROOFLINE_CELLS:
        record = factory()
        streams = {
            canonical(_roofline_estimate(provider, record, sampled))
            for _ in range(REPEATS)
        }
        rows.append(
            Row(
                f"G1-{row_id}",
                FATAL_GUARD,
                "repeat determinism, roofline",
                f"{label},repeats={REPEATS}",
                1,
                len(streams),
            )
        )
    for row_id, bandwidth, sm_count, _ in MECHANISTIC_CELLS:
        model = mechanistic_model(hbm_bandwidth=bandwidth, sm_count=sm_count)
        launch = mechanistic_launch()
        streams = {canonical(model.estimate(launch)) for _ in range(REPEATS)}
        rows.append(
            Row(
                f"G1-{row_id}",
                FATAL_GUARD,
                "repeat determinism, mechanistic",
                f"bw={bandwidth},sms={sm_count},repeats={REPEATS}",
                1,
                len(streams),
            )
        )


def guard_fresh_instance_determinism(rows: list[Row]) -> None:
    """G2: a freshly built provider produces the same byte string."""

    for row_id, label, factory, sampled in ROOFLINE_CELLS:
        record = factory()
        first = canonical(_roofline_estimate(roofline(), record, sampled))
        second = canonical(_roofline_estimate(roofline(), factory(), sampled))
        rows.append(
            Row(
                f"G2-{row_id}",
                FATAL_GUARD,
                "fresh-instance determinism, roofline",
                label,
                first.decode("utf-8"),
                second.decode("utf-8"),
            )
        )
    for row_id, bandwidth, sm_count, _ in MECHANISTIC_CELLS:
        first = canonical(
            mechanistic_model(
                hbm_bandwidth=bandwidth, sm_count=sm_count
            ).estimate(mechanistic_launch())
        )
        second = canonical(
            mechanistic_model(
                hbm_bandwidth=bandwidth, sm_count=sm_count
            ).estimate(mechanistic_launch())
        )
        rows.append(
            Row(
                f"G2-{row_id}",
                FATAL_GUARD,
                "fresh-instance determinism, mechanistic",
                f"bw={bandwidth},sms={sm_count}",
                first.decode("utf-8"),
                second.decode("utf-8"),
            )
        )


def guard_host_identity(rows: list[Row]) -> None:
    """G3: the ideal host profile adds exactly zero to every R cell."""

    ideal = HostInitiationModel.ideal()
    provider = roofline()
    for row_id, label, factory, sampled in ROOFLINE_CELLS:
        estimate = _roofline_estimate(provider, factory(), sampled)
        composed = ideal.represented_estimate(estimate, gpu_spec())
        rows.append(
            Row(
                f"G3-{row_id}",
                FATAL_GUARD,
                "ideal host profile is the exact identity",
                label,
                [estimate.duration_ps, 0],
                [composed.duration_ps, composed.exposed_ps],
            )
        )


def guard_no_nondeterminism_source(rows: list[Row]) -> None:
    """G4: no compute module imports an RNG, a clock or an environment reader."""

    rows.append(
        Row(
            "G4",
            FATAL_GUARD,
            "no nondeterminism source in simllm/compute",
            "AST import audit",
            {},
            nondeterminism_audit(),
        )
    )


def guard_no_identity_parameter(rows: list[Row]) -> None:
    """G5: no pricing entry point accepts a rank, worker or adapter identity."""

    rows.append(
        Row(
            "G5",
            FATAL_GUARD,
            "no caller identity in a pricing signature",
            f"{len(pricing_entry_points())} entry points",
            {},
            identity_parameter_audit(),
        )
    )


def _peer_port(protocol: GpuPortProtocol) -> None:
    GpuPortConfig(
        port_id=f"{protocol.value}-peer-store",
        protocol=protocol,
        role=GpuPortRole.PEER_LINK,
        direction=GpuPortDirection.EGRESS,
        capabilities=(GpuPortCapability.PEER_STORE_EGRESS,),
    )


def guard_unprofiled_protocols_fail_closed(rows: list[Row]) -> None:
    """G6: xGMI and UALink are nameable and rejected at configuration time."""

    for protocol in (GpuPortProtocol.XGMI, GpuPortProtocol.UALINK):
        try:
            _peer_port(protocol)
        except ValueError as error:
            measured = "COMP-35" in str(error)
        else:
            measured = False
        rows.append(
            Row(
                f"G6-{protocol.value}",
                FATAL_GUARD,
                "unprofiled peer protocol fails closed naming its owner",
                protocol.value,
                True,
                measured,
            )
        )
    # Naming a protocol must not make it selectable anywhere else.
    rows.append(
        Row(
            "G6-nvlink",
            FATAL_GUARD,
            "the profiled peer protocol is unaffected",
            "nvlink peer store still constructs",
            True,
            _nvlink_port_constructs(),
        )
    )


def _nvlink_port_constructs() -> bool:
    try:
        _peer_port(GpuPortProtocol.NVLINK)
    except ValueError:
        return False
    return True


def control_efficiency_changes_the_byte_stream(rows: list[Row]) -> None:
    """C1: G1's byte equality is discriminating."""

    record = decode_record(2)
    baseline = canonical(_roofline_estimate(roofline(), record, 2))
    mutated = canonical(_roofline_estimate(roofline(efficiency=0.25), record, 2))
    rows.append(
        Row(
            "C1",
            CONTROL,
            "a changed efficiency changes the byte stream",
            "decode,requests=2,efficiency=0.25",
            True,
            baseline != mutated,
        )
    )


def control_geometry_changes_the_price(rows: list[Row]) -> None:
    """C2: the adapter agreement below is discriminating."""

    from simllm.adapters.sglang.worker import model_dims_from_sglang

    record = decode_record(2)
    baseline = _price(model_dims_from_sglang(sglang_model_config(), tp_size=1), record, 2)
    mutated = _price(model_dims_from_sglang(sglang_model_config(), tp_size=2), record, 2)
    rows.append(
        Row(
            "C2",
            CONTROL,
            "a changed geometry changes the price",
            "sglang tp_size=2",
            True,
            baseline != mutated,
        )
    )


def control_bandwidth_changes_the_duration(rows: list[Row]) -> None:
    """C3: the mechanistic pin is a measurement, not a printed constant."""

    fast = mechanistic_model(hbm_bandwidth=64, sm_count=1).estimate(mechanistic_launch())
    slow = mechanistic_model(hbm_bandwidth=32, sm_count=1).estimate(mechanistic_launch())
    rows.append(
        Row(
            "C3",
            CONTROL,
            "a changed cursor bandwidth changes the duration",
            "bw=64 against bw=32",
            True,
            fast.duration_cycles != slow.duration_cycles,
        )
    )


def _price(dims: ModelDims, record: StepRecord, sampled: int) -> int:
    return estimate_step_latency_ps(
        dims,
        record,
        sampled,
        roofline(),
        gpu_spec(),
        HostInitiationModel.ideal(),
    )


def scored_phase_and_token_keying(rows: list[Row]) -> None:
    """Family A: phase and token shape move the constant, to exact values."""

    provider = roofline()
    for row_id, label, factory, sampled in ROOFLINE_CELLS:
        estimate = _roofline_estimate(provider, factory(), sampled)
        expected_ps, expected_bound = ROOFLINE_PREDICTIONS[row_id]
        rows.append(
            Row(
                row_id,
                SCORED,
                "phase and token keying, roofline closed form",
                label,
                [expected_ps, expected_bound],
                [estimate.duration_ps, estimate.bound],
            )
        )


def scored_memory_bound_pin(rows: list[Row]) -> None:
    """Families B and C: the pin on the flat HBM cursor."""

    for row_id, bandwidth, sm_count, expected_cycles in MECHANISTIC_CELLS:
        estimate = mechanistic_model(
            hbm_bandwidth=bandwidth, sm_count=sm_count
        ).estimate(mechanistic_launch())
        family = (
            "memory-bound pin on the HBM cursor"
            if row_id.startswith("B")
            else "the pin ignores SM count"
        )
        rows.append(
            Row(
                row_id,
                SCORED,
                family,
                f"bytes={MECHANISTIC_TRANSACTION_BYTES},bw={bandwidth},sms={sm_count}",
                [expected_cycles, expected_cycles * 1_000],
                [estimate.duration_cycles, estimate.duration_ps],
            )
        )


def scored_adapter_agreement(rows: list[Row]) -> None:
    """Family D: the two geometry readers agree on the cost geometry."""

    vllm_dims, sglang_dims = adapter_dims()
    rows.append(
        Row(
            "D1",
            SCORED,
            "runner and adapter independence",
            "vllm reader against sglang reader, dense, tp=1",
            cost_geometry(vllm_dims),
            cost_geometry(sglang_dims),
        )
    )


def derived_rows(rows: list[Row]) -> None:
    """Arithmetic over scored rows. Reported, never counted."""

    measured = {row.row_id: row.measured for row in rows if row.evidence_class == SCORED}
    a1_ps, a2_ps = measured["A1"][0], measured["A2"][0]
    a3_ps, a4_ps = measured["A3"][0], measured["A4"][0]
    b1_cycles, b2_cycles = measured["B1"][0], measured["B2"][0]

    kv_delta_bytes = 2 * 128 * NUM_LAYERS * NUM_KV_HEADS * HEAD_SIZE * DTYPE_BYTES
    rows.append(
        Row(
            "DER-1",
            DERIVED,
            "A2 minus A1 is the KV read delta",
            f"{kv_delta_bytes} bytes at the derated roof",
            int(kv_delta_bytes / (MEM_BANDWIDTH * EFFICIENCY) * 1e12),
            a2_ps - a1_ps,
        )
    )
    rows.append(
        Row(
            "DER-2",
            DERIVED,
            "prefill is superlinear in chunk length",
            "A4 over A3, four decimal places",
            2.6144,
            round(a4_ps / a3_ps, 4),
        )
    )
    rows.append(
        Row(
            "DER-3",
            DERIVED,
            "the cursor term scales inversely with bandwidth",
            "B2 minus latency against twice B1 minus latency",
            2 * (b1_cycles - TASK_MIX.HBM_LATENCY),
            b2_cycles - TASK_MIX.HBM_LATENCY,
        )
    )

    vllm_dims, sglang_dims = adapter_dims()
    record = decode_record(2)
    rows.append(
        Row(
            "DER-4",
            DERIVED,
            "equal geometry prices to equal picoseconds",
            "vllm reader against sglang reader",
            _price(vllm_dims, record, 2),
            _price(sglang_dims, record, 2),
        )
    )
    rows.append(
        Row(
            "DER-5",
            DERIVED,
            "the frozen decode value reaches both adapters",
            "A1 predicted picoseconds",
            ROOFLINE_PREDICTIONS["A1"][0],
            _price(vllm_dims, record, 2),
        )
    )


def observations(rows: list[Row]) -> None:
    """Raw configuration facts. These assert nothing."""

    dims = model_dims()
    vllm_dims, sglang_dims = adapter_dims()
    rows.append(
        Row(
            "OBS-1",
            OBSERVATION,
            "fixture R geometry",
            "weight and lm-head bytes",
            None,
            [dims.weight_bytes, dims.lm_head_bytes],
        )
    )
    for row_id, label, factory, sampled in ROOFLINE_CELLS:
        kernel = step_kernel(dims, factory(), sampled)
        rows.append(
            Row(
                f"OBS-{row_id}",
                OBSERVATION,
                "fused kernel work",
                label,
                None,
                [int(kernel.flops), int(kernel.bytes_moved), list(kernel.config)],
            )
        )
    rows.append(
        Row(
            "OBS-2",
            OBSERVATION,
            "the two readers spell the optional dtype widths differently",
            "weight_dtype_bytes and kv_dtype_bytes as stored",
            None,
            [
                [vllm_dims.weight_dtype_bytes, vllm_dims.kv_dtype_bytes],
                [sglang_dims.weight_dtype_bytes, sglang_dims.kv_dtype_bytes],
            ],
        )
    )
    rows.append(
        Row(
            "OBS-3",
            OBSERVATION,
            "peer-link protocols the taxonomy can name",
            "protocol values",
            None,
            sorted(protocol.value for protocol in GpuPortProtocol),
        )
    )
    rows.append(
        Row(
            "OBS-4",
            OBSERVATION,
            "pricing entry points covered by guard G5",
            "audited names",
            None,
            sorted(pricing_entry_points()),
        )
    )


def collect_rows() -> list[Row]:
    rows: list[Row] = []
    guard_repeat_determinism(rows)
    guard_fresh_instance_determinism(rows)
    guard_host_identity(rows)
    guard_no_nondeterminism_source(rows)
    guard_no_identity_parameter(rows)
    guard_unprofiled_protocols_fail_closed(rows)
    control_efficiency_changes_the_byte_stream(rows)
    control_geometry_changes_the_price(rows)
    control_bandwidth_changes_the_duration(rows)
    scored_phase_and_token_keying(rows)
    scored_memory_bound_pin(rows)
    scored_adapter_agreement(rows)
    derived_rows(rows)
    observations(rows)
    return rows


def summarize(rows: list[Row]) -> dict[str, Any]:
    guards = [row for row in rows if row.evidence_class == FATAL_GUARD]
    controls = [row for row in rows if row.evidence_class == CONTROL]
    scored = [row for row in rows if row.evidence_class == SCORED]
    derived = [row for row in rows if row.evidence_class == DERIVED]
    violated = [row.row_id for row in guards if not row.passed]
    return {
        "fatal_guards": len(guards),
        "fatal_guards_violated": violated,
        "void": bool(violated),
        "controls": len(controls),
        "controls_failed": [row.row_id for row in controls if not row.passed],
        "scored_total": len(scored),
        "scored_passed": sum(1 for row in scored if row.passed),
        "scored_failed": [row.row_id for row in scored if not row.passed],
        "derived_reported": len(derived),
        "derived_failed": [row.row_id for row in derived if not row.passed],
    }


def build_payload() -> dict[str, Any]:
    rows = collect_rows()
    return {
        "schema": SCHEMA,
        "freeze": FREEZE,
        "fixtures": {
            "roofline_geometry": _plain(model_dims()),
            "roofline_gpu": _plain(gpu_spec()),
            "roofline_efficiency": EFFICIENCY,
            "host_profile": "ideal",
            "mechanistic_source": "examples/gpu_task_mix/run_gpu_task_mix.py",
            "mechanistic_transaction_bytes": MECHANISTIC_TRANSACTION_BYTES,
            "mechanistic_hbm_latency_cycles": TASK_MIX.HBM_LATENCY,
            "repeats": REPEATS,
        },
        "rows": [row.to_json() for row in rows],
        "summary": summarize(rows),
    }


def render(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, sort_keys=False) + "\n"


def transcript(payload: dict[str, Any]) -> str:
    lines = ["kernel_determinism_v1", f"freeze: {payload['freeze']}", ""]
    for row in payload["rows"]:
        lines.append(
            f"{row['status']:8s} {row['evidence_class']:12s} {row['id']:10s} "
            f"{row['family']} [{row['case']}]"
        )
    summary = payload["summary"]
    lines.append("")
    if summary["void"]:
        lines.append(f"VOID: fatal guards violated: {summary['fatal_guards_violated']}")
    else:
        lines.append(f"all {summary['fatal_guards']} fatal guards held")
    lines.append(
        f"scored {summary['scored_passed']} of {summary['scored_total']}"
        f"; controls {summary['controls'] - len(summary['controls_failed'])}"
        f" of {summary['controls']}"
        f"; derived rows reported: {summary['derived_reported']}"
    )
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="require the regenerated artifact to equal the committed bytes",
    )
    parser.add_argument("--out", type=Path, default=RESULTS)
    args = parser.parse_args(argv)

    payload = build_payload()
    rendered = render(payload)
    print(transcript(payload), end="")

    if args.check:
        if not args.out.exists():
            print(f"missing committed artifact {args.out}")
            return 1
        committed = args.out.read_bytes()
        if committed != rendered.encode("utf-8"):
            print(f"artifact {args.out} does not reproduce byte for byte")
            return 1
    else:
        args.out.write_text(rendered, encoding="utf-8", newline="\n")

    summary = payload["summary"]
    if summary["void"] or summary["controls_failed"] or summary["scored_failed"]:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
