"""Pluggable compute-time providers.

The core needs one number per GOAL ``calc`` node: how long a rank computes
before it hands data over and releases its successor. Different fidelity
levels answer that question at very different cost, so the provider is a
plugin interface (:class:`ComputeProvider`) rather than a fixed model:

============================  ================================================
Provider                      Fidelity / cost
============================  ================================================
:class:`ProfileTableProvider` Measured (kernel, config) → duration tables from
                              real captures. Cheap, accurate on covered points.
:class:`RooflineProvider`     Analytical ``max(flops/peak, bytes/bw)``:
                              classifies compute- vs memory-bound from the
                              kernel configuration alone. Cheap, coarse.
:class:`TraceCalibratedGpuProvider`
                              Deterministic CTA, warp, pipeline, memory, and
                              copy-service replay. Replays once at provider
                              construction; online estimates are cached.
External Accel-Sim            Offline SASS trace replay used to calibrate and
                              cross-check immutable profile tables.
============================  ================================================

The DP dependency chain the user-visible simulation executes (receive data
plus a small start packet, compute, hand data over, write a small packet to
release the next rank) is exactly GOAL's ``recv``/``calc``/``send`` chain
with ``requires`` edges; providers only supply the ``calc`` durations.

Host-side initiation (doorbells) is modeled separately in
:mod:`simllm.compute.host`.
"""

from simllm.compute.calibration import (
    COMPUTE_CALIBRATION_SCHEMA,
    HELD_OUT_SPLIT,
    TRAIN_SPLIT,
    CapturePlanCell,
    ComputeCalibrationArtifact,
    ComputeCalibrationProvenance,
    KernelCaptureCell,
    KernelLaunchMetadata,
    absolute_percentage_error,
    calibration_artifact_to_profile_table,
    held_out_errors,
    nearest_rank,
    parse_nsight_cuda_gpu_trace_csv,
    parse_nsight_cuda_gpu_trace_csvs,
    physical_duration_bounds_ps,
    sha256_file,
)
from simllm.compute.gpu_device import (
    GPU_DEVICE_CONFIG_VERSION,
    GPU_DEVICE_IMPLEMENTATION,
    GPU_PORT_CONFIG_VERSION,
    MECHANISM_CAPABILITIES,
    TRANSPORT_CONTROL_CAPABILITIES,
    GpuDevice,
    GpuDeviceConfig,
    GpuPort,
    GpuPortApplicability,
    GpuPortCapability,
    GpuPortCeiling,
    GpuPortCeilingProvenance,
    GpuPortConfig,
    GpuPortDirection,
    GpuPortProtocol,
    GpuPortReport,
    GpuPortRole,
    default_gpu_device_config,
)
from simllm.compute.gpu_model import (
    GPU_MODEL_IMPLEMENTATION,
    CopyDirection,
    CopyDirectionProfile,
    CopyEngineProfile,
    CopyEngineServiceModel,
    CopyServiceEstimate,
    CopyTransfer,
    CtaTrace,
    GpuArchitectureProfile,
    GpuCalibrationProfile,
    GpuConcurrentEstimate,
    GpuKernelEstimate,
    GpuModelProvenance,
    GpuTask,
    GpuTaskEstimate,
    GpuTaskKind,
    KernelLaunch,
    MemoryHierarchyProfile,
    MemorySpace,
    MixedMakespanForm,
    MixedMakespanRegime,
    NvlinkProfile,
    PipelineKind,
    PipelineProfile,
    SassInstruction,
    SassWarpTrace,
    SmSchedulerModel,
    TraceCalibratedGpuProvider,
    WarpSchedulerPolicy,
    a100_sxm_80gb_seed_profile,
    decompose_mixed_makespan,
    h100_sxm_80gb_seed_profile,
)
from simllm.compute.gpu_model_io import (
    GPU_MODEL_ARTIFACT_SCHEMA,
    CalibrationSplit,
    GpuCaptureEnvironment,
    GpuCopyReplayRecord,
    GpuKernelCatalogRecord,
    GpuMeasurementRecord,
    GpuModelArtifact,
    GpuReplayRecord,
    gpu_model_artifact_from_json,
    gpu_model_artifact_to_json,
    gpu_model_artifact_to_profile_table,
    load_gpu_model_artifact,
    save_gpu_model_artifact,
)
from simllm.compute.host import HostInitiationModel, HostStepEstimate
from simllm.compute.nccl import (
    NCCL_RING_EGRESS_IMPLEMENTATION,
    nccl_ring_allreduce_launch,
    nccl_ring_allreduce_task,
    nccl_ring_egress_bytes,
)
from simllm.compute.nccl_stack import (
    NCCL_STACK_EVENT_SCHEMA,
    NcclCollectiveResult,
    NcclRegistrationResult,
    NcclRoute,
    NcclStack,
    NcclStackConfig,
    NcclStackEvent,
    NcclStackEventKind,
    NcclStackLane,
    nccl_stack_event_from_json,
    nccl_stack_event_to_json,
    nccl_stack_events_from_json,
    nccl_stack_events_to_json,
    ncclAllReduce,
    ncclCommInitRank,
    ncclNetRegMr,
    validate_nccl_stack_events,
)
from simllm.compute.provider import (
    PROFILE_TABLE_SCHEMA,
    PS_PER_SECOND,
    ComputeProvider,
    DurationEstimate,
    GpuSpec,
    KernelSpec,
    ProfileTableProvenance,
    ProfileTableProvider,
    RooflineProvider,
)
from simllm.compute.rnic import (
    RNIC_PRODUCER_IMPLEMENTATION,
    RnicProducerCoupling,
    RnicProducerRequest,
    RnicProducerSchedule,
    RnicProducerShape,
    RnicProducerTaskLink,
    RnicSubmissionScheduleEntry,
    rnic_submission_producer_task,
)
from simllm.compute.transformer import (
    GPU_ENVELOPES,
    ModelDims,
    estimate_step_latency_ps,
    step_kernel,
    step_kernels,
    step_shape,
)

__all__ = [
    "COMPUTE_CALIBRATION_SCHEMA",
    "GPU_DEVICE_CONFIG_VERSION",
    "GPU_DEVICE_IMPLEMENTATION",
    "GPU_ENVELOPES",
    "GPU_MODEL_ARTIFACT_SCHEMA",
    "GPU_MODEL_IMPLEMENTATION",
    "GPU_PORT_CONFIG_VERSION",
    "HELD_OUT_SPLIT",
    "MECHANISM_CAPABILITIES",
    "NCCL_RING_EGRESS_IMPLEMENTATION",
    "NCCL_STACK_EVENT_SCHEMA",
    "PROFILE_TABLE_SCHEMA",
    "PS_PER_SECOND",
    "RNIC_PRODUCER_IMPLEMENTATION",
    "TRAIN_SPLIT",
    "TRANSPORT_CONTROL_CAPABILITIES",
    "CalibrationSplit",
    "CapturePlanCell",
    "ComputeCalibrationArtifact",
    "ComputeCalibrationProvenance",
    "ComputeProvider",
    "CopyDirection",
    "CopyDirectionProfile",
    "CopyEngineProfile",
    "CopyEngineServiceModel",
    "CopyServiceEstimate",
    "CopyTransfer",
    "CtaTrace",
    "DurationEstimate",
    "GpuArchitectureProfile",
    "GpuCalibrationProfile",
    "GpuCaptureEnvironment",
    "GpuConcurrentEstimate",
    "GpuCopyReplayRecord",
    "GpuDevice",
    "GpuDeviceConfig",
    "GpuKernelCatalogRecord",
    "GpuKernelEstimate",
    "GpuMeasurementRecord",
    "GpuModelArtifact",
    "GpuModelProvenance",
    "GpuPort",
    "GpuPortApplicability",
    "GpuPortCapability",
    "GpuPortCeiling",
    "GpuPortCeilingProvenance",
    "GpuPortConfig",
    "GpuPortDirection",
    "GpuPortProtocol",
    "GpuPortReport",
    "GpuPortRole",
    "GpuReplayRecord",
    "GpuSpec",
    "GpuTask",
    "GpuTaskEstimate",
    "GpuTaskKind",
    "HostInitiationModel",
    "HostStepEstimate",
    "KernelCaptureCell",
    "KernelLaunch",
    "KernelLaunchMetadata",
    "KernelSpec",
    "MemoryHierarchyProfile",
    "MemorySpace",
    "MixedMakespanForm",
    "MixedMakespanRegime",
    "ModelDims",
    "NcclCollectiveResult",
    "NcclRegistrationResult",
    "NcclRoute",
    "NcclStack",
    "NcclStackConfig",
    "NcclStackEvent",
    "NcclStackEventKind",
    "NcclStackLane",
    "NvlinkProfile",
    "PipelineKind",
    "PipelineProfile",
    "ProfileTableProvenance",
    "ProfileTableProvider",
    "RnicProducerCoupling",
    "RnicProducerRequest",
    "RnicProducerSchedule",
    "RnicProducerShape",
    "RnicProducerTaskLink",
    "RnicSubmissionScheduleEntry",
    "RooflineProvider",
    "SassInstruction",
    "SassWarpTrace",
    "SmSchedulerModel",
    "TraceCalibratedGpuProvider",
    "WarpSchedulerPolicy",
    "a100_sxm_80gb_seed_profile",
    "absolute_percentage_error",
    "calibration_artifact_to_profile_table",
    "decompose_mixed_makespan",
    "default_gpu_device_config",
    "estimate_step_latency_ps",
    "gpu_model_artifact_from_json",
    "gpu_model_artifact_to_json",
    "gpu_model_artifact_to_profile_table",
    "h100_sxm_80gb_seed_profile",
    "held_out_errors",
    "load_gpu_model_artifact",
    "ncclAllReduce",
    "ncclCommInitRank",
    "ncclNetRegMr",
    "nccl_ring_allreduce_launch",
    "nccl_ring_allreduce_task",
    "nccl_ring_egress_bytes",
    "nccl_stack_event_from_json",
    "nccl_stack_event_to_json",
    "nccl_stack_events_from_json",
    "nccl_stack_events_to_json",
    "nearest_rank",
    "parse_nsight_cuda_gpu_trace_csv",
    "parse_nsight_cuda_gpu_trace_csvs",
    "physical_duration_bounds_ps",
    "rnic_submission_producer_task",
    "save_gpu_model_artifact",
    "sha256_file",
    "step_kernel",
    "step_kernels",
    "step_shape",
    "validate_nccl_stack_events",
]
