"""Render the task-progress block in docs/README_PRO.md from tracked files.

Open IDs come from the open-task sections of docs/modules/*.md; closed IDs
come from docs/task-ledger.json. The two sets together are every task ever
registered. Nothing here reads git history, so it works in shallow CI
checkouts.

    python3 scripts/task_progress.py            # print the block
    python3 scripts/task_progress.py --check    # fail if README_PRO drifted
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
MODULES = REPO_ROOT / "docs" / "modules"
LEDGER = REPO_ROOT / "docs" / "task-ledger.json"
README_PRO = REPO_ROOT / "docs" / "README_PRO.md"

BEGIN = "<!-- task-progress: generated by scripts/task_progress.py, do not hand edit -->"
END = "<!-- end task-progress -->"

PREFIXES = (
    "CORE",
    "WORK",
    "COMP",
    "PLACE",
    "TRAF",
    "GOAL",
    "PLAY",
    "BACK",
    "VLLM",
    "SGL",
    "BRIDGE",
    "HTSIM",
    "ATLAHS",
)
# Module doc -> the ID prefixes it owns, in the order the status table lists them.
OWNERS = (
    ("core", ("CORE", "BRIDGE")),
    ("workload", ("WORK",)),
    ("compute", ("COMP",)),
    ("placement", ("PLACE",)),
    ("traffic", ("TRAF",)),
    ("goal", ("GOAL",)),
    ("preplay", ("PLAY",)),
    ("backends", ("BACK", "HTSIM", "ATLAHS")),
    ("adapters-vllm", ("VLLM",)),
    ("adapters-sglang", ("SGL",)),
)

_BULLET = re.compile(r"^-\s+(" + "|".join(PREFIXES) + r")-(\d+)\b")
# A second-level heading opens the task lists; only another second-level
# heading closes them, so the "### Precision" subheadings stay inside.
_OPEN_HEADING = re.compile(r"^##\s+(Open tasks|Backend-repo follow-ups)", re.IGNORECASE)
_TOP_HEADING = re.compile(r"^##\s")


def open_ids(text: str) -> set[str]:
    found: set[str] = set()
    inside = False
    for line in text.split("\n"):
        if _OPEN_HEADING.match(line):
            inside = True
            continue
        if inside and _TOP_HEADING.match(line):
            inside = False
            continue
        if inside:
            match = _BULLET.match(line)
            if match:
                found.add(f"{match.group(1)}-{match.group(2)}")
    return found


def collect() -> tuple[dict[str, set[str]], set[str], list[str]]:
    per_module = {
        path.stem: open_ids(path.read_text(encoding="utf-8"))
        for path in sorted(MODULES.glob("*.md"))
    }
    ledger = json.loads(LEDGER.read_text(encoding="utf-8"))
    closed = set(ledger["closed"])
    return per_module, closed, sorted(ledger.get("retracted", ()))


def bar(done: int, total: int, width: int = 28) -> str:
    if total <= 0:
        return "`" + "░" * width + "`"
    filled = round(width * done / total)
    return "`" + "█" * filled + "░" * (width - filled) + "`"


def render() -> str:
    per_module, closed, retracted = collect()
    open_all = set().union(*per_module.values()) if per_module else set()
    conflict = sorted(open_all & closed)
    if conflict:
        raise SystemExit(
            "these IDs are listed closed in docs/task-ledger.json but still have "
            f"an open module entry: {', '.join(conflict)}"
        )

    def split(prefixes: tuple[str, ...]) -> tuple[int, int]:
        def owned(ids: set[str]) -> int:
            return sum(1 for i in ids if i.rsplit("-", 1)[0] in prefixes)

        return owned(closed), owned(open_all)

    total_done, total_open = len(closed), len(open_all)
    total = total_done + total_open
    lines = [
        BEGIN,
        "",
        (
            f"**{total_done} of {total} registered tasks closed.** "
            f"{total_open} remain open across ten modules."
        ),
        "",
        f"{bar(total_done, total)} {round(100 * total_done / total)} percent",
        "",
        "| Module | Closed | Registered | Progress |",
        "|---|---:|---:|---|",
    ]
    for name, prefixes in OWNERS:
        done, still_open = split(prefixes)
        module_total = done + still_open
        lines.append(
            f"| [{name}](modules/{name}.md) | {done} | {module_total} | "
            f"{bar(done, module_total, 18)} |"
        )
    note = (
        "Counted from the open-task sections of the module docs plus the closed "
        "list in [task-ledger.json](task-ledger.json); regenerate with "
        "`python3 scripts/task_progress.py`. A task is registered when a change "
        "defers work and closed when the completing change removes its entry, so "
        "the denominator grows as the build-out discovers work: a rising open "
        "count is not a regression."
    )
    if retracted:
        note += (
            f" {' and '.join(retracted)} was retracted by maintainer decision "
            "rather than completed, and is counted as closed."
        )
    lines += ["", note, "", END]
    return "\n".join(lines)


def status_table_errors() -> list[str]:
    """Check the module-status table's open-task cell against the module docs.

    The cell used to list IDs by hand and drifted badly: closed IDs stayed in
    it for whole waves. It now carries only a count, which this check keeps
    honest.
    """
    per_module, _, _ = collect()
    text = README_PRO.read_text(encoding="utf-8")
    # The generated progress table above uses the same row prefix, so only the
    # module-status section counts here.
    _, separator, table = text.partition("## Module status")
    if not separator:
        return ["docs/README_PRO.md has no module-status section"]
    errors = []
    for name, prefixes in OWNERS:
        row = re.search(
            rf"^\| \[{re.escape(name)}\]\(modules/{re.escape(name)}\.md\) \|.*$",
            table,
            re.MULTILINE,
        )
        if row is None:
            errors.append(f"{name}: no module-status row")
            continue
        cell = row.group(0).rsplit("|", 2)[1].strip()
        expected_count = sum(
            1 for i in per_module.get(name, ()) if i.rsplit("-", 1)[0] in prefixes
        )
        if expected_count == 0:
            expected = "none"
        else:
            expected = f"[{expected_count} open](modules/{name}.md#open-tasks)"
        if cell != expected:
            errors.append(f"{name}: open cell is {cell!r}, expected {expected!r}")
    return errors


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify docs/README_PRO.md matches the regenerated block",
    )
    arguments = parser.parse_args()
    block = render()
    if not arguments.check:
        print(block)
        return
    text = README_PRO.read_text(encoding="utf-8")
    if BEGIN not in text or END not in text:
        raise SystemExit("docs/README_PRO.md has no task-progress block")
    current = text[text.index(BEGIN) : text.index(END) + len(END)]
    problems = [] if current == block else ["the task-progress block is stale"]
    problems += status_table_errors()
    if problems:
        for problem in problems:
            sys.stderr.write(f"{problem}\n")
        sys.stderr.write("regenerate with python3 scripts/task_progress.py\n")
        raise SystemExit(1)
    print("task-progress block and module-status open counts are current")


if __name__ == "__main__":
    main()
