"""Backend-free deployment candidate, estimator, and frontier contracts."""

from simllm.deploy.candidate import (
    BUDGET_GPUS_EXCEEDED,
    BUDGET_NODES_EXCEEDED,
    DEPLOYMENT_CANDIDATE_SCHEMA,
    HBM_CAPACITY_EXCEEDED,
    PIPELINE_PARALLEL_UNPRICED,
    BudgetSpec,
    DeploymentCandidate,
    FabricSpec,
    FeasibilityReport,
    ModelRef,
    PoolSpec,
    SlaSpec,
    WorkloadPoint,
    candidate_from_json,
    candidate_key,
    candidate_to_json,
    check_feasibility,
    from_json,
    to_json,
)

__all__ = [
    "BUDGET_GPUS_EXCEEDED",
    "BUDGET_NODES_EXCEEDED",
    "DEPLOYMENT_CANDIDATE_SCHEMA",
    "HBM_CAPACITY_EXCEEDED",
    "PIPELINE_PARALLEL_UNPRICED",
    "BudgetSpec",
    "DeploymentCandidate",
    "FabricSpec",
    "FeasibilityReport",
    "ModelRef",
    "PoolSpec",
    "SlaSpec",
    "WorkloadPoint",
    "candidate_from_json",
    "candidate_key",
    "candidate_to_json",
    "check_feasibility",
    "from_json",
    "to_json",
]
